/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Certificate Report Frame
package GUI;
import ConnectionClass.ConnectionClass;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class CertificateReportframe extends javax.swing.JFrame {
 ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;
JTable table;
JScrollPane scroll;
DefaultTableModel model;

    /**
     * Creates new form CertificateReportframe
     */
    public CertificateReportframe() {
        initComponents();
        model=new DefaultTableModel();
        model.addColumn("Citizen Name");
         model.addColumn("Aadhar Id");
        model.addColumn("Center Name");
        model.addColumn("Medicine Name");
         model.addColumn("DOV one");
          model.addColumn("DOV two");
           model.addColumn("Certificate Number");
            model.addColumn("Issue Date");
        model.addColumn("Status");
        table=new JTable(model);
        scroll=new JScrollPane(table);
        scroll.setBounds(50,100,600,350);
        add(scroll);
         cobj = new ConnectionClass();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showButton = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CertificateReportFrame_CVCM");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Calendar-icon (1).png")); // NOI18N
        jLabel1.setText("From Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Calendar-icon.png")); // NOI18N
        jLabel2.setText("To Date");

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(showButton)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(showButton)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(453, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
         cobj.Connect();
        for(int count=model.getRowCount()-1;count>=0;count--)
            model.removeRow(count);
         try
        {
            pst=cobj.con.prepareStatement("SELECT        dbo.tbCitizen.Name, dbo.tbCitizen.AadharID, dbo.tbCenter.Name AS Expr1, dbo.tbMedicine.MedicineName, dbo.tbDosage.DOVOne, dbo.tbDosage.DOVTwo, dbo.tbCertificate.CertiNo, dbo.tbCertificate.IssueDate, \n" +
"                         dbo.tbCertificate.Status " +
"FROM            dbo.tbCertificate INNER JOIN " +
"                         dbo.tbDosage ON dbo.tbCertificate.DosageID = dbo.tbDosage.DosageID INNER JOIN " +
"                         dbo.tbCitizen ON dbo.tbDosage.CitizenID = dbo.tbCitizen.CitizenID INNER JOIN " +
"                         dbo.tbCenter ON dbo.tbDosage.CenterID = dbo.tbCenter.CenterId INNER JOIN " +
"                         dbo.tbMedicine ON dbo.tbDosage.MedicineID = dbo.tbMedicine.MedicineID where IssueDate>=? and IssueDate<=?");
        pst.setString(1,tf1.getText());
        pst.setString(2,tf2.getText());
        rst=pst.executeQuery();
        while(rst.next())
        {
            model.insertRow(model.getRowCount(), new Object[]
                    {
                rst.getString(1),
                rst.getString(2),
                rst.getString(3),
                rst.getString(4),
                rst.getString(5),
                rst.getString(6),
                rst.getString(7),
                rst.getString(8),
                rst.getString(9),
                });
        }
        rst.close();
    }
     catch(Exception ex)
        {
            System.out.println("Error in table data"+ ex);
        }
        cobj.Disconnect();// TODO add your handling code here:
    }//GEN-LAST:event_showButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertificateReportframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertificateReportframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertificateReportframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertificateReportframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new CertificateReportframe().setVisible(true);
                  CertificateReportframe obj=new CertificateReportframe();
                obj.setLocation(300,120);
                        obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton showButton;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
