/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import ConnectionClass.ConnectionClass;
import ConnectionClass.ArraySearch;
import java.sql.*;
/**
 *
 * @author LENOVO
 */
public class Dosage extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;
long CenterId[];
long CitizenId[];
long MedicineId[];
long DosageId;
    /**
     * Creates new form Dosage
     */
    public Dosage() {
        initComponents();
        cobj=new ConnectionClass();
        CenterId=new long[100];
        int index=0;
        cobj.Connect();
        try
        {
            pst=cobj.con.prepareStatement("select CenterId,Name from tbCenter");
            rst=pst.executeQuery();
            while(rst.next())
            {
                CenterId[index]=rst.getLong(1);
                index++;
                combo1.addItem(rst.getString(2));
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("error in combo populate"+ex);
        }
        cobj.Disconnect();
         CitizenId=new long[100];
        index=0;
        cobj.Connect();
        try
        {
            pst=cobj.con.prepareStatement("select CitizenId,Name from tbCitizen");
            rst=pst.executeQuery();
            while(rst.next())
            {
                CitizenId[index]=rst.getLong(1);
                index++;
               // combo2.addItem(rst.getString(2));
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("error in combo populate"+ex);
        }
        cobj.Disconnect();
         MedicineId=new long[100];
        index=0;
        cobj.Connect();
        try
        {
            pst=cobj.con.prepareStatement("select MedicineId,MedicineName from tbMedicine");
            rst=pst.executeQuery();
            while(rst.next())
            {
                MedicineId[index]=rst.getLong(1);
                index++;
                combo3.addItem(rst.getString(2));
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("error in combo populate"+ex);
        }
        cobj.Disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        tf5 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        lab1 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lab14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CVCM_DOSAGE");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\k-word-kwd-icon.png")); // NOI18N
        jLabel2.setText("Select Center");

        jLabel3.setText("Name");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\User-Black-Folder-icon.png")); // NOI18N
        jLabel4.setText("Select Medicine");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Calendar-alt-icon (1).png")); // NOI18N
        jLabel5.setText("DOV One");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Calendar-icon (1).png")); // NOI18N
        jLabel6.setText("Time One");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Calendar-icon.png")); // NOI18N
        jLabel7.setText("Next Date");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Time-And-Date-Today-icon.png")); // NOI18N
        jLabel8.setText("DOV Two");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Time-Date-From-icon.png")); // NOI18N
        jLabel9.setText("Time Two");

        savebutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\save.png")); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        SearchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\Search-icon.png")); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        UpdateButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\update.png")); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\reset.png")); // NOI18N
        jButton4.setText("Reset");

        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb1);
        rb1.setText("Dose1");
        rb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb1ItemStateChanged(evt);
            }
        });
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb2);
        rb2.setText("Dose2");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\sign-check-icon (1).png")); // NOI18N
        jLabel1.setText("Select Dosage");

        jLabel10.setText("Father's Name");

        jLabel12.setText("Address");

        jLabel13.setText("Phone Number");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resources\\resources\\User-Executive-Blue-icon.png")); // NOI18N
        jLabel15.setText("Aadhar Id");

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Citizen Details");

        jLabel11.setText("Citizen Id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel9))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))
                        .addGap(372, 372, 372))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24)
                        .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lab14, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(rb2))
                                    .addComponent(tf5)
                                    .addComponent(tf3)
                                    .addComponent(tf2)
                                    .addComponent(tf4)
                                    .addComponent(tf1)
                                    .addComponent(combo3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(rb1)
                                    .addComponent(rb2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(lab14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel18)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebutton)
                    .addComponent(SearchButton)
                    .addComponent(UpdateButton)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        cobj.Connect();
        try
        {
            pst =cobj.con.prepareCall("{call prcInsertDosage(?,?,?,?,?,?,?,?)}");
            pst.setLong(1,CenterId[combo1.getSelectedIndex()]);
            pst.setLong(2,Long.parseLong(lab14.getText()));
            pst.setLong(3,MedicineId[combo3.getSelectedIndex()]);
             pst.setString(4, tf1.getText());
            pst.setString(5, tf2.getText());
            pst.setString(6,  tf3.getText());
            pst.setString(7,  tf4.getText());
            pst.setString(8,  tf5.getText());
            
            if(pst.execute()==false)
                if(pst.getUpdateCount()>0)
                {
                    lab1.setText("Record Saved Successfully");
                    tf1.setText("");
                    tf2.setText("");
                    tf3.setText("");
                    tf4.setText("");
                     tf5.setText("");
                }
              }
        catch(Exception ex)
        {
            System.out.println("Error in insert issue "+ex);
        }
        cobj.Disconnect();// TODO add your handling code here:
    }//GEN-LAST:event_savebuttonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        cobj.Connect();
        try
        {
            pst =cobj.con.prepareCall("{call prcUpdateDosage(?,?,?,?,?,?,?,?,?)}");
           pst.setLong(1, DosageId);
            pst.setLong(2, CenterId[combo1.getSelectedIndex()]);
             pst.setLong(3,Long.parseLong(lab14.getText()));
              pst.setLong(4,MedicineId[combo3.getSelectedIndex()]);
            pst.setString(5,tf1.getText());
            pst.setString(6,tf2.getText());
            pst.setString(7,tf3.getText());
             pst.setString(8,tf4.getText());
            pst.setString(9,tf5.getText());
            if(pst.execute()==false)
                if(pst.getUpdateCount()>0)
                {
                    lab1.setText("Record Updated Successfully");
                    tf1.setText("");
                    tf2.setText("");
                    tf3.setText("");
                   tf4.setText("");
                   tf5.setText("");
                }
        }
        catch(Exception ex)
        {
            System.out.println("Error in update issue "+ex);
        }
        cobj.Disconnect();       // TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
          cobj.Connect();
        try
        {
            pst = cobj.con.prepareStatement("Select * from tbCitizen where  AadharId =?");
            pst.setString(1, tf6.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                lab14.setText(rst.getString(1).trim());
                L1.setText(rst.getString(2).trim());
                L2.setText(rst.getString(3).trim());
                L3.setText(rst.getString(4).trim());
                L4.setText(rst.getString(5).trim());
                 
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("Error in search "+ex);
        }
         try
        {
            pst = cobj.con.prepareStatement("SELECT dbo.tbDosage.DosageID, dbo.tbDosage.CenterID, dbo.tbDosage.MedicineID, dbo.tbDosage.DOVOne, dbo.tbDosage.TimeOne, dbo.tbDosage.NextDate, dbo.tbDosage.DOVTwo, dbo.tbDosage.TimeTwo\n" +
"FROM            dbo.tbDosage INNER JOIN\n" +
"dbo.tbCitizen ON dbo.tbDosage.CitizenID = dbo.tbCitizen.CitizenID where AadharID=?");
            pst.setString(1, tf6.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                  rb2.setSelected(true);
                 
               DosageId= rst.getLong(1);
                combo1.setSelectedIndex(new ArraySearch().searchArray(CenterId, rst.getLong(2)));
                combo3.setSelectedIndex(new ArraySearch().searchArray(MedicineId, rst.getLong(3)));
                
                tf1.setText(rst.getString(4).trim());
                tf2.setText(rst.getString(5).trim());
                tf3.setText(rst.getString(6).trim());
                tf4.setText(rst.getString(7).trim());
                 tf5.setText(rst.getString(8).trim()); 
                 tf1.setEnabled(false);
                 tf2.setEnabled(false);
                  tf3.setEnabled(false);
                 tf4.setEnabled(true);
                  tf5.setEnabled(true);
            }
            else{
                rb1.setSelected(true);
                 tf1.setEnabled(true);
                 tf2.setEnabled(true);
                  tf3.setEnabled(true);
                  tf4.setEnabled(false);
                  tf5.setEnabled(false);
            }
                
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("Error in search "+ex);
        }
        
        cobj.Disconnect();   // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
             cobj.Connect();
        try
        {
            pst = cobj.con.prepareStatement("Select * from tbCitizen where  AadharId =?");
            pst.setString(1, tf6.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
             //  DosageId= rst.getLong(1);
               // combo1.setSelectedIndex(new ArraySearch().searchArray(CenterId, rst.getLong(2)));
                //combo2.setSelectedIndex(new ArraySearch().searchArray(CitizenId, rst.getLong(3)));
               // combo3.setSelectedIndex(new ArraySearch().searchArray(MedicineId, rst.getLong(4)));
                lab14.setText(rst.getString(1).trim());
                L1.setText(rst.getString(2).trim());
                L2.setText(rst.getString(3).trim());
                L3.setText(rst.getString(4).trim());
                L4.setText(rst.getString(5).trim());
                 
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("Error in search "+ex);
        }
         try
        {
            pst = cobj.con.prepareStatement("SELECT dbo.tbDosage.DOVOne, dbo.tbDosage.TimeOne, dbo.tbDosage.NextDate, dbo.tbDosage.DOVTwo, dbo.tbDosage.TimeTwo " +
"FROM dbo.tbDosage INNER JOIN dbo.tbCitizen ON dbo.tbDosage.CitizenID = dbo.tbCitizen.CitizenID where AadharId=?");
            pst.setString(1, tf6.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
                  rb2.setSelected(true);
                 
             //  DosageId= rst.getLong(1);
               // combo1.setSelectedIndex(new ArraySearch().searchArray(CenterId, rst.getLong(2)));
                //combo2.setSelectedIndex(new ArraySearch().searchArray(CitizenId, rst.getLong(3)));
               // combo3.setSelectedIndex(new ArraySearch().searchArray(MedicineId, rst.getLong(4)));
                
                tf1.setText(rst.getString(1).trim());
                tf2.setText(rst.getString(2).trim());
                tf3.setText(rst.getString(3).trim());
                tf4.setText(rst.getString(4).trim());
                 tf5.setText(rst.getString(5).trim()); 
                 tf1.setEnabled(false);
                 tf2.setEnabled(false);
                  tf3.setEnabled(false);
                 tf4.setEnabled(true);
                  tf5.setEnabled(true);
            }
            else{
                rb1.setSelected(true);
                 tf1.setEnabled(true);
                 tf2.setEnabled(true);
                  tf3.setEnabled(true);
                  tf4.setEnabled(false);
                  tf5.setEnabled(false);
            }
                
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("Error in search "+ex);
        }
        
        cobj.Disconnect();                    // TODO add your handling code here:
        
    }//GEN-LAST:event_tf6ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb1ItemStateChanged
                cobj.Connect();
        try
        {
            pst = cobj.con.prepareStatement("Select * from tbDosage ");
            pst.setString(1, tf6.getText());
            rst=pst.executeQuery();
            if(rst.next())
            {
             //  DosageId= rst.getLong(1);
               // combo1.setSelectedIndex(new ArraySearch().searchArray(CenterId, rst.getLong(2)));
                //combo2.setSelectedIndex(new ArraySearch().searchArray(CitizenId, rst.getLong(3)));
               // combo3.setSelectedIndex(new ArraySearch().searchArray(MedicineId, rst.getLong(4)));
                tf1.setText(rst.getString(5).trim());
                tf2.setText(rst.getString(6).trim());
                tf3.setText(rst.getString(7).trim());
                tf4.enable(false);
                  tf5.enable(false);
            }
            rst.close();
        }
        catch(Exception ex)
        {
            System.out.println("Error in search "+ex);
        }
        cobj.Disconnect();                    // TODO add your handling code here:
        
            // TODO add your handling code here:
    }//GEN-LAST:event_rb1ItemStateChanged

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dosage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dosage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dosage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dosage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Dosage().setVisible(true);
                 Dosage obj=new Dosage();
                obj.setLocation(300,80);
                        obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab14;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
